export function langdata(key){
    var lang={
        zh_CN:{
            ps:"平",
            ying:"赢",
            zyj:"总押金",
            szsl:"收注数量",
            bzj:"保证金",

            gpkyf:"该盘口已封",
            fzcg:"复制成功",
            ddjxz:"订单进行中",
            djz:"待结账",
            ddywc:"订单已完成",
            ddyqx:"订单已取消",
            jzsb:"结账失败",
            ddcsgb:"订单超时关闭",
            ddslz:"订单上链中",
            ddslsx:"订单上链失效",

            qxkp:"取消开盘",
            jr:"今日",
            zp:"早盘",
            gj:"冠军",
            rm:"热门",
            sg:"赛果",
            wskp:"请先完善开盘数据",
            yyqh:"语言切换",
            zxkf:"在线客服",
            czma:"重置密码",
            sz:"设置",
            jysy:"交易收益",
            tdsy:"团队收益",
            pm:"排名",
            jrxz:"今日新增",
            tdrs:"团队人数",
            ztrs:"直推人数",
            wdtd:"我的团队",
            yqm:"邀请码",
            yqhy:"邀请好友",
            gxxyd:"该消息已读",
            txxwd:"条未读消息",
            gg:"公告",
            wdyqm:"我的邀请码",
            wdyhk:"我的银行卡",
            dldj:"代理等级",
            sjhm:"手机号码",
            dsf:"待释放",
            bet:"BET",
            usdtsd:"usdt锁定",
            usdtye:"usdt余额",
            wd:"我的",
            grxx:"个人信息",
            tx:"头像",
            mz:"名字",
            xgyhm:"修改用户名",
            yhm:"用户名",
            qsryhm:"请输入用户名",
            tjxg:"提交修改",
            dqdj:"当前等级",

            ssss:"搜索赛事",
            jt:"今天",
            mt:"明天",
            ht:"后天",
            wlyz:"未来一周",
            wlyy:"未来一月",
            gy:"更远",
            tz:"投注",
            kp:"开盘",
            qc:"全场",
            rf:"让分",
            dx:"大小",
            lx:"类型",
            qcjg:"全场结果",
            dw:"队伍",
            pl:"赔率",
            kpz:"开盘者",
            tzje:"投注金额",
            yjsy:"预计收益",
            fy:"费用",
            pz:"批准",
            fw:"范围",
            sy:"收益",
            qr:"确认",
            syrq:"所有日期",
            qcdy:"全场独赢",
            qcbf:"全场让球",
            qcdx:"全場大小",
            yebz:"余额不足",
            zd:"最大",
            zgky:"最高可赢",
            pj:"平局",
            zhye:"账户余额",
            tzd:"投注单",
            wdtz:"我的投注",
            ks:"客胜",
            zs:"主胜",
            wf:"玩法",
            jjc:"奖金池",
            kpr:"开盘人",
            yzje:"押注金额",

            jyjl:"交易记录",
            sl:"胜率",
            sx:"筛选",
            ylqk:"盈利情況",
            qb:"全部",
            wks:"未开赛",
            jxz:"进行中",
            yws:"已完赛",
            yqx:"已取消",
            yyq:"已延期",
            ylye:"盈利余额",
            rqxz:"日期选择",
            br:"本日",
            bz:"本周",
            by:"本月",
            bn:"本年",
            xzfw:"选择范围",
            qsrq:"起始日期",
            zzrq:"终止日期",
            zsy:"总收益",
            zds:"总单数",
            qbxz:"全部选择",
            dg:"单，共",
            zt:"状态",
            tzrs:"投注人数",
            tzzj:"投注资金",
            qkid:"区块ID",
            jyhx:"交易哈希",
            sj:"时间",
            fx:"分享",
            jlsj:"距离升级",
            hc:"还差",
            czz:"成长值",
            jrsy:"今日收益",
            sjgl:"升级攻略",
            ksxs:"亏损显示",
            ksyc:"亏损隐藏",
            ddh:"订单号",
        },
        zh_HK:{
            ying:"赢",
            ps:"平",
            zyj:"總押金",
            szsl:"收注數量",
            bzj:"保證金",
            gpkyf:"該盤口已封盤",
            fzcg:"複製成功",
            ddjxz:"訂單進行中",
            djz:"待結賬",
            ddywc:"訂單已完成",
            ddyqx:"訂單已取消",
            jzsb:"結賬失敗",
            ddcsgb:"訂單超時關閉",
            ddslz:"訂單上鍊中",
            ddslsx:"訂單上鍊失效",

            qxkp:"取消開盤",
            jr:"今日",
            zp:"早盤",
            gj:"冠軍",
            rm:"熱門",
            sg:"賽果",
            wskp:"請先完善開盤數據",
            yyqh:"語言切換",
            zxkf: "在線客服",
            czma:"重置密碼",
            sz:"設置",
            tdsy:"團隊收益",
            jysy: "交易收益",
            pm:"排名",
            jrxz:"今日新增",
            tdrs:"團隊人數",
            ztrs:"直推人數",
            wdtd:"我的團隊",
            yqm:"邀請碼",
            yqhy:"邀請好友",
            gxxyd:"該消息已讀",
            txxwd:"條未讀消息",
            gg:"公告",
            wdyqm:"我的邀請碼",
            wdyhk:"我的銀行卡",
            dldj:"代理等級",
            sjhm:"手機號碼",
            dsf:"待釋放",
            bet:"BET",
            usdtsd:"usdt鎖定",
            usdtye:"usdt餘額",
            wd:"我的",
            grxx:"個人信息",
            tx:"头像",
            mz:"名字",
            xgyhm:"修改用户名",
            yhm:"用户名",
            qsryhm:"請輸入用戶名",
            tjxg:"提交修改",
            dqdj:"當前等級",

            ssss:"搜索賽事",
            jt:"今天",
            mt:"明天",
            ht:"後天",
            wlyz:"未来一周",
            wlyy:"未来一月",
            gy:"更遠",
            tz:"投注",
            kp:"開盤",
            qc:"全場",
            rf:"讓分",
            dx:"大小",
            lx:"類型",
            qcjg:"全場結果",
            dw:"隊伍",
            pl:"賠率",
            kpz:"開盤者",
            tzje:"投注金额",
            yjsy:"預計收益",
            fy:"费用",
            pz:"批准",
            fw:"範圍",
            sy:"收益",
            qr:"確認",
            syrq:"所有日期",
            qcdy:"全場獨贏",
            qcbf:"全場讓球",
            qcdx:"全場大小",
            yebz:"余额不足",
            zd:"最大",
            zgky:"最高可赢",
            pj:"平局",
            zhye:"賬戶餘額",
            tzd:"投注單",
            wdtz:"我的投注",
            ks:"客勝",
            zs:"主勝",
            wf:"玩法",
            jjc:"獎金池",
            kpr:"開盤人",
            yzje:"押註金額",

            jyjl:"交易記錄",
            sl:"勝率",
            sx:"篩選",
            ylqk:"盈利情況",
            qb:"全部",
            wks:"未開賽",
            jxz:"進行中",
            yws:"已完赛",
            yqx:"已取消",
            yyq:"已延期",
            ylye:"盈利余额",
            rqxz:"日期選擇",
            br:"本日",
            bz:"本週",
            by:"本月",
            bn:"本年",
            xzfw:"選擇範圍",
            qsrq:"起始日期",
            zzrq:"終止日期",
            zsy:"總收益",
            zds:"總單數",
            qbxz:"全部選擇",
            dg:"單，共",
            zt:"状态",
            tzrs:"投注人數",
            tzzj:"投注資金",
            qkid:"區塊ID",
            jyhx:"交易哈希",
            sj:"時間",
            fx:"分享",
            jlsj:"距離升級",
            hc:"還差",
            czz:"成長值",
            jrsy:"今日收益",
            sjgl:"升級攻略",
            ksxs:"虧損顯示",
            ksyc:"虧損隱藏",
            ddh:"訂單號",
        },
        en_US:{
            ps:"TIE",
            ying:"WIN",
            zyj:"Total Margin",
            szsl:"Margin",
            bzj:"Profit/Bet",
            gpkyf:"This game has been closed",
            fzcg:"Copy Success",
            ddjxz:"Order In Progress",
            djz:"To Check Out",
            ddywc:"Has Been Completed",
            ddyqx:"Has Been Cancelled",
            jzsb:"Checkout Failed",
            ddcsgb:"Timeout Closure",
            ddslz:"In The Chain",
            ddslsx:"Chain On The Failure",

            qxkp:"Cancel The Opening",
            jr:"Today",
            zp:"Early Game",
            gj:"Champion",
            rm:"Popular",
            sg:"Result",
            wskp:"Please Improve The Opening Data First",
            yyqh:"Language Switch",
            zxkf:"Online Service",
            czma:"Reset Password",
            sz:"Set Up",
            tdsy:"Team Benefits",
            jysy: "Trading Income",
            pm:"ranking",
            jrxz:"Added Today",
            tdrs:"Team Size",
            ztrs:"Direct Push Number",
            wdtd:"My Team",
            yqm:"Invitation Code",
            yqhy:"invite Friends",
            gxxyd:"The Message Has Been Read",
            txxwd:"Unread messages",
            gg:"Announcement",
            wdyqm:"My Invitation Code",
            wdyhk:"My Bank Card",
            dldj:"Agency Level",
            sjhm:"Phone Number",
            dsf:"Pending Release",
            bet:"BET",
            usdtsd:"Usdt Lock",
            usdtye:"Usdt Balance",
            wd:"Mine",
            grxx:"Personal Information",
            tx:"Head Portrait",
            mz:"Name",
            xgyhm:"Changing A User Name",
            yhm:"User Name",
            qsryhm:"Please Enter A User Name",
            tjxg:"Commit Changes",
            dqdj:"The Current Level",

            ssss:"Search For Events",
            jt:"Today",
            mt:"Tomorrow",
            ht:"After Tomorrow",
            wlyz:"Next Week",
            wlyy:"Next Month",
            gy:"Farther",
            tz:"Bet",
            kp:"Opening",
            qc:"The Audience",
            rf:"Handicap",
            dx:"Size",
            lx:"Type",
            qcjg:"Fulltime Results",
            dw:"Team",
            pl:"Odds",
            kpz:"Provider",
            tzje:"Bet Amount",
            yjsy:"Expected Earnings",
            fy:"Cost",
            pz:"Approve",
            fw:"Scope",
            sy:"Income",
            qr:"Confirm",
            syrq:"All The Date",
            qcdy:"Double Win",
            qcbf:"Full Handicap",
            qcdx:"Full Size",
            yebz:"Lack Of Balance",
            zd:"MAX",
            zgky:"MAX WIN",
            pj:"Draw",
            zhye:"The Account Balance",
            tzd:"Betting List",
            wdtz:"My Betting",
            ks:"Guest",
            zs:"Host",
            wf:"Type",
            jjc:"Capital",
            kpr:"Provider",
            yzje:"Stock",

            jyjl:"Transaction Record",
            sl:"Win Rate",
            sx:"Filter",
            ylqk:"Profitability",
            qb:"All",
            wks:"Not Started",
            jxz:"In Progress",
            yws:"Finished",
            yqx:"Cancelled",
            yyq:"Paused",
            ylye:"Profit Amount",
            rqxz:"Date Selection",
            br:"Today",
            bz:"This Week",
            by:"This Month",
            bn:"This Year",
            xzfw:"Options",
            qsrq:"start Date",
            zzrq:"expiry Date",
            zsy:"Total Revenue",
            zds:"Total Odd",
            qbxz:"Select All",
            dg:"Orders，Total",
            zt:"State",
            tzrs:"Bet The Number",
            tzzj:"Spend Money",
            qkid:"Block ID",
            jyhx:"Trading Hash",
            sj:"Time",
            fx:"Share",
            jlsj:"Distance To Upgrade ",
            hc:" Less",
            czz:"Growth Value ",
            jrsy:"Today Benefits",
            sjgl:"Upgrade Strategy",
            ksxs:"Display Losses",
            ksyc:"Hidden Losses",
            ddh:"Order Number",
        },
        ja_JP:{
            zyj:"総敷金",
            ying:"胜",
            ps:"平",
            szsl:"マージン",
            bzj:"利益/賭け",
            gpkyf:"このスロットは閉鎖されました",
            fzcg:"複製に成功する",
            ddjxz:"注文進行中",
            djz:"会計待ち",
            ddywc:"注文は完了した",
            ddyqx:"取り消しになった",
            jzsb:"失敗する",
            ddcsgb:"タイムアウト閉鎖",
            ddslz:"上鎖中",
            ddslsx:"チェーンダウン",

            qxkp:"寄り付きを取り消す",
            jr:"今日",
            zp:"早く盤",
            gj:"優勝",
            rm:"ヒット",
            sg:"赛果",
            wskp:"まずは寄り付きデータを補完してください",
            yyqh:"言語の切り替え",
            zxkf:"オンラインカスタマーサービス",
            czma:"パスワードのリセット",
            sz:"設定",
            jysy:"取引収益",
            tdsy:"チームの利益",
            pm:"ランキング",
            jrxz:"本日の追加",
            tdrs:"チームの規模",
            ztrs:"人数を直押しする",
            wdtd:"私のチーム",
            yqm:"招待コード",
            yqhy:"友達を招待します",
            gxxyd:"既読メッセージ",
            txxwd:"未読メッセージ",
            gg:"お知らせ",
            wdyqm:"私の招待コード",
            wdyhk:"私の銀行カード",
            dldj:"代理店レベル",
            sjhm:"電話番号",
            dsf:"リリース待ち",
            bet:"BET",
            usdtsd:"USDTロック",
            usdtye:"USDT残高",
            wd:"マイページ",
            grxx:"個人情報",
            tx:"颜を",
            mz:"なまえ",
            xgyhm:"ユーザーめー名をへんこー変更する",
            yhm:"ユーザーめー名",
            qsryhm:"ユーザーめー名をにゅーりょく入力してください",
            tjxg:"しゅーせー修正をてーしゅつ提出する",
            dqdj:"げんざい現在のとーきゅー等級",

            ssss:"レースけんさく検索",
            jt:"今日",
            mt:"明日",
            ht:"明後日",
            wlyz:"来週",
            wlyy:"来月",
            gy:"さらに",
            tz:"ベット",
            kp:"オープン",
            qc:"フルタイム",
            rf:"ハンディキャップ",
            dx:"サイズ",
            lx:"タイプ",
            qcjg:"フルタイムの結果",
            dw:"チーム",
            pl:"オッズ",
            kpz:"オープナー",
            tzje:"ベット金額",
            yjsy:"予想利益",
            fy:"コスト",
            pz:"承認",
            fw:"範囲",
            sy:"収益",
            qr:"確認",
            syrq:"すべてのひずけ日付",
            qcdy:"全試合単独勝利",
            qcbf:"フルセットでボールを許す",
            qcdx:"満場の大きさ",
            yebz:"残高が足りない",
            zd:"さいだい",
            zgky:"最高で勝つ",
            pj:"引き分け",
            zhye:"こーざざんだか",
            tzd:"賭け伝票",
            wdtz:"私の賭け",
            ks:"客勝",
            zs:"主勝",
            wf:"コンビニ",
            jjc:"ボーナスプール",
            kpr:"寄り付き人",
            yzje:"金額に賭ける",

            jyjl:"トランザクションレコード",
            sl:"勝率",
            sx:"選別",
            ylqk:"儲け具合",
            qb:"すべて",
            wks:"未開幕",
            jxz:"進行中",
            yws:"すでに試合を終えた",
            yqx:"取り消しになった",
            yyq:"延期された",
            ylye:"くろじざんだか",
            rqxz:"日付選択",
            br:"本の日",
            bz:"今週",
            by:"今月",
            bn:"本年",
            xzfw:"選択範囲",
            qsrq:"開始日",
            zzrq:"終了期日",
            zsy:"総収益",
            zds:"総単数",
            qbxz:"すべて選択する",
            dg:"単,共",
            zt:"状态",
            tzrs:"ベッティング人数",
            tzzj:"資金を賭ける",
            qkid:"ブロックID",
            jyhx:"トランザクションハッシュ",
            sj:"时间",
            fx:"分かち合い",
            jlsj:"距離アップグレード",
            hc:"まだ",
            czz:"成長値",
            jrsy:"今日の収益",
            sjgl:"ランクアップ攻略",
            ksxs:"赤字表示",
            ksyc:"赤字隠し",
            ddh:"注文書番号",
        },
        ms_MY:{
            zyj:"Jumlah deposit",
            ying:"Menang",
            ps:"Rata",
            szsl:"Margin",
            bzj:"Untung/Bertaruh",
            gpkyf:"Permainan ini telah ditutup",

            fzcg:"Replikasi Berjaya",
            ddjxz:"Sedang Berjalan",
            djz:"Menunggu Pembayaran",
            ddywc:"Dilakukan",
            ddyqx:"Dibatalkan",
            jzsb:"Pembayaran Gagal",
            ddcsgb:"Penutupan Tamat Masa",
            ddslz:"Dalam Rantaian",
            ddslsx:"Gagal Berliku",

            qxkp:"Batalkan Pembukaan",
            jr:"Hari Ini",
            zp:"Pasaran Awal",
            gj:"Juara",
            rm:"Panas",
            sg:"Keputusan",
            wskp:"Sila perhalusi data pembukaan terlebih dahulu",
            yyqh:"Tukar Bahasa",
            zxkf:"Helpdesk Dalam Talian",
            czma:"Reset Kata Laluan",
            sz:"Set Up",
            jysy:"Pendapatan",
            tdsy:"Faedah Pasukan",
            pm:"Ranking",
            jrxz:"Ditambah Hari Ini",
            tdrs:"Saiz Pasukan",
            ztrs:"Penaja Langsung",
            wdtd:"Pasukan Saya",
            yqm:"Kod Jemputan",
            yqhy:"Jemput Kawan",
            gxxyd:"Mesej Telah Dibaca",
            txxwd:"Mesej Telah Dibaca",
            gg:"Pengumuman",
            wdyqm:"Kod Jemputan Saya",
            wdyhk:"Sad Bank Saya",
            dldj:"Tahap Agensi",
            sjhm:"Nombor Telefon",
            dsf:"Tunggu Pelepasan",
            bet:"BET",
            usdtsd:"USDT Dikuncikan",
            usdtye:"Baki USDT",
            wd:"Halaman saya",
            grxx:"Maklumat Peribadi",
            tx:"Avatar",
            mz:"Nama",
            xgyhm:"Ubah Suai Nama Pengguna",
            yhm:"Nama Pengguna",
            qsryhm:"Sila Masukkan Nama Pengguna",
            tjxg:"Lakukan Perubahan",
            dqdj:"Aras Semasa",

            ssss:"Cari Peristiwa",
            jt:"Hari Ini",
            mt:"Esok",
            ht:"Hari Selepas Esok",
            wlyz:"Minggu Depan",
            wlyy:"Datang Pada Bulan Januari",
            gy:"Lebih Jauh Lagi",
            tz:"Pertaruhan",
            kp:"Membuka",
            qc:"Tempat Penuh",
            rf:"Kecacatan",
            dx:"Saiz",
            lx:"Jenis",
            qcjg:"Keputusan Sepenuh Masa",
            dw:"Luarjangka",
            pl:"Kemungkinan",
            kpz:"Pembuka",
            tzje:"Amaun Pertaruhan",
            yjsy:"Pendapatan Yang Dijangkakan",
            fy:"Perbelanjaan",
            pz:"Meluluskan",
            fw:"Pelbagai",
            sy:"Pendapatan",
            qr:"Mengesahkan",
            syrq:"Semua Tarikh",
            qcdy:"Tempat Penuh",
            qcbf:"Cacal Penuh",
            qcdx:"Saiz penuh",
            yebz:"Baki tidak Mencukupi",
            zd:"Terbaik",
            zgky:"Kemenangan Tertinggi",
            pj:"Menarik",
            zhye:"Baki Akaun",
            tzd:"Slip Pertaruhan",
            wdtz:"Pertaruhan Saya",
            ks:"Menang",
            zs:"Tuhan Menang",
            wf:"Bermain",
            jjc:"Kolam Bonus",
            kpr:"Pembuka",
            yzje:"Amaun Pertaruhan",

            jyjl:"Sejarah Transaksi",
            sl:"Peratusan Kemenangan",
            sx:"Ayak",
            ylqk:"Keuntungan",
            qb:"Semua",
            wks:"Tiada Bermula",
            jxz:"Pemprosesan",
            yws:"Selesai",
            yqx:"Dibatalkan",
            yyq:"Dilanjutkan",
            ylye:"Baki Keuntungan",
            rqxz:"Pemilihan Tarikh",
            br:"Hari Ini",
            bz:"Minggu",
            by:"Bulan",
            bn:"Tahun",
            xzfw:"Pilih Skop",
            qsrq:"Tarikh Mula",
            zzrq:"Tarikh Penamatan",
            zsy:"Jumlah Hasil",
            zds:"Jumlah Tunggal",
            qbxz:"Pilih Semua",
            dg:"Bujang, Jumlah",
            zt:"Negeri",
            tzrs:"Bilangan Penjudi",
            tzzj:"Bertaruh Wang",
            qkid:"ID Blok",
            jyhx:"Pencincangan Transaksi",
            sj:"Masa",
            fx:"Berkongsi",
            jlsj:"Naik Taraf Jarak",
            hc:"Boleh Tahan",
            czz:"Nilai Pertumbuhan",
            jrsy:"Pendapatan Hari Ini",
            sjgl:"Naik Taraf Raiders",
            ksxs:"Kerugian Dipaparkan",
            ksyc:"Kerugian Tersembunyi",
            ddh:"Nombor Pesanan",
        }
    };
    return lang[key];
}
