package yijiang.jboot.model;

import com.jfinal.plugin.activerecord.Model;
import io.jboot.db.annotation.Table;

/**
 * Generated by JFinal.
 */
@Table(tableName = "revenue_record", primaryKey = "id")
public class RevenueRecord extends Model<RevenueRecord> {
	private static final long serialVersionUID = 1L;
	public static final RevenueRecord dao = new RevenueRecord().dao();
}
