package yijiang.jboot.model;

import com.jfinal.plugin.activerecord.Model;
import io.jboot.db.annotation.Table;

/**
 * Generated by JFinal.
 */
@Table(tableName = "user_wallet", primaryKey = "id")
public class UserWallet extends Model<UserWallet> {
	private static final long serialVersionUID = 1L;
	public static final UserWallet dao = new UserWallet().dao();
}
